$(document).ready(function()
                  {
                      $("#btnList").click(function()
                                          {
                                              $("#MAPVIEW").show();
                                              $("#LISTVIEW").show();
                                          });
                      $("#btnMap").click(function()
                                         {
                                             $("#MAPVIEW").show();
                                             $("#btnList").show();
                                             $(".btnCreate").show();
                                             $("#LISTVIEW").hide();
                                         });
                      $(".btnCreate").click(function()
                                            {
                                                $("#MAPVIEW").show();
                                                $("#LISTVIEW").hide();
                                                $("#btnList").hide();
                                                $(".btnCreate").hide();
                                                $("#NEWEVENT").show();
                                            });
                      $("#btnBack").click(function()
                                          {
                                              $("#MAPVIEW").show();
                                              $("#btnList").show();
                                              $(".btnCreate").show();
                                              $("#NEWEVENT").hide();
                                          });
                      $("#closeGloo").click(function()
                                            {
                                                $("#GLOOPADVIEW").hide();
                                                $("#MAPVIEW").show();
                                                $("#btnMap").show();
                                                $(".btnCreate").show();
                                                $("#NEWEVENT").hide();
                                                $("#LISTVIEW").show();
                                            });
                  });
